# Generated by Django 3.2.8 on 2022-08-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crud2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=255, verbose_name='nombre')),
                ('correo', models.CharField(max_length=255, verbose_name='nombre')),
                ('telefono', models.CharField(max_length=255, verbose_name='nombre')),
                ('estado', models.CharField(max_length=255, verbose_name='estado')),
            ],
        ),
    ]
