# Generated by Django 3.2.8 on 2022-08-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud2',
            name='apellido',
            field=models.CharField(max_length=255, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='crud2',
            name='correo',
            field=models.CharField(max_length=255, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='crud2',
            name='telefono',
            field=models.CharField(max_length=255, verbose_name='telefono'),
        ),
    ]
